"""empty message

Revision ID: 1e1871b38650
Revises: c2c93e2e28c6
Create Date: 2021-06-23 12:38:55.020576

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1e1871b38650'
down_revision = 'c2c93e2e28c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('title', sa.String(length=150), nullable=False))
    op.add_column('history', sa.Column('public_id', sa.String(length=150), nullable=False))
    op.add_column('history', sa.Column('image_url', sa.String(length=150), nullable=False))
    op.drop_index('history_key', table_name='history')
    op.drop_index('token_vacune', table_name='history')
    op.create_unique_constraint(None, 'history', ['public_id'])
    op.create_unique_constraint(None, 'history', ['image_url'])
    op.drop_column('history', 'vacune')
    op.drop_column('history', 'history_key')
    op.drop_column('history', 'token_vacune')
    op.drop_column('history', 'history')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('history', mysql.VARCHAR(length=150), nullable=False))
    op.add_column('history', sa.Column('token_vacune', mysql.VARCHAR(length=150), nullable=False))
    op.add_column('history', sa.Column('history_key', mysql.VARCHAR(length=150), nullable=False))
    op.add_column('history', sa.Column('vacune', mysql.VARCHAR(length=150), nullable=False))
    op.drop_constraint(None, 'history', type_='unique')
    op.drop_constraint(None, 'history', type_='unique')
    op.create_index('token_vacune', 'history', ['token_vacune'], unique=False)
    op.create_index('history_key', 'history', ['history_key'], unique=False)
    op.drop_column('history', 'image_url')
    op.drop_column('history', 'public_id')
    op.drop_column('history', 'title')
    # ### end Alembic commands ###
