"""empty message

Revision ID: 51b152d18633
Revises: 1e1871b38650
Create Date: 2021-06-23 12:46:01.164973

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '51b152d18633'
down_revision = '1e1871b38650'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacune',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('public_id', sa.String(length=150), nullable=False),
    sa.Column('image_url', sa.String(length=150), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('pet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pet.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_url'),
    sa.UniqueConstraint('public_id')
    )
    op.add_column('photo_add', sa.Column('title', sa.String(length=150), nullable=False))
    op.add_column('photo_add', sa.Column('public_id', sa.String(length=150), nullable=False))
    op.add_column('photo_add', sa.Column('image_url', sa.String(length=150), nullable=False))
    op.drop_index('token_image', table_name='photo_add')
    op.create_unique_constraint(None, 'photo_add', ['public_id'])
    op.create_unique_constraint(None, 'photo_add', ['image_url'])
    op.drop_column('photo_add', 'token_image')
    op.drop_column('photo_add', 'images')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo_add', sa.Column('images', mysql.VARCHAR(length=150), nullable=False))
    op.add_column('photo_add', sa.Column('token_image', mysql.VARCHAR(length=150), nullable=False))
    op.drop_constraint(None, 'photo_add', type_='unique')
    op.drop_constraint(None, 'photo_add', type_='unique')
    op.create_index('token_image', 'photo_add', ['token_image'], unique=False)
    op.drop_column('photo_add', 'image_url')
    op.drop_column('photo_add', 'public_id')
    op.drop_column('photo_add', 'title')
    op.drop_table('vacune')
    # ### end Alembic commands ###
