"""empty message

Revision ID: 61a72c0b5cd0
Revises: 916b7d51df04
Create Date: 2021-06-09 04:36:55.571423

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '61a72c0b5cd0'
down_revision = '916b7d51df04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length=40), nullable=False))
    op.add_column('user', sa.Column('user_name', sa.String(length=40), nullable=False))
    op.add_column('user', sa.Column('phone', sa.String(length=12), nullable=False))
    op.add_column('user', sa.Column('birtday', sa.String(length=11), nullable=False))
    op.add_column('user', sa.Column('country', sa.String(length=40), nullable=False))
    op.add_column('user', sa.Column('city', sa.String(length=40), nullable=False))
    op.create_unique_constraint(None, 'user', ['user_name'])
    op.create_unique_constraint(None, 'user', ['phone'])
    op.create_unique_constraint(None, 'user', ['birtday'])
    op.create_unique_constraint(None, 'user', ['country'])
    op.create_unique_constraint(None, 'user', ['city'])
    op.create_unique_constraint(None, 'user', ['name'])
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'city')
    op.drop_column('user', 'country')
    op.drop_column('user', 'birtday')
    op.drop_column('user', 'phone')
    op.drop_column('user', 'user_name')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
