"""empty message

Revision ID: 84c8851b9753
Revises: 26b1cce2e59b
Create Date: 2021-06-15 16:49:23.445929

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '84c8851b9753'
down_revision = '26b1cce2e59b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('pet_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'history', 'pet', ['pet_id'], ['id'])
    op.drop_constraint('pet_ibfk_1', 'pet', type_='foreignkey')
    op.drop_constraint('pet_ibfk_2', 'pet', type_='foreignkey')
    op.drop_column('pet', 'history_id')
    op.drop_column('pet', 'photo_add_id')
    op.add_column('photo_add', sa.Column('pet_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'photo_add', 'pet', ['pet_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'photo_add', type_='foreignkey')
    op.drop_column('photo_add', 'pet_id')
    op.add_column('pet', sa.Column('photo_add_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pet', sa.Column('history_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('pet_ibfk_2', 'pet', 'photo_add', ['photo_add_id'], ['id'])
    op.create_foreign_key('pet_ibfk_1', 'pet', 'history', ['history_id'], ['id'])
    op.drop_constraint(None, 'history', type_='foreignkey')
    op.drop_column('history', 'pet_id')
    # ### end Alembic commands ###
