"""empty message

Revision ID: 943bb97e68be
Revises: 88574fe20324
Create Date: 2021-06-09 22:10:04.663431

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '943bb97e68be'
down_revision = '88574fe20324'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_name', sa.String(length=40), nullable=False))
    op.add_column('user', sa.Column('name', sa.String(length=40), nullable=False))
    op.add_column('user', sa.Column('last_name', sa.String(length=40), nullable=False))
    op.add_column('user', sa.Column('phone', sa.String(length=12), nullable=False))
    op.add_column('user', sa.Column('birthday', sa.String(length=11), nullable=False))
    op.add_column('user', sa.Column('country', sa.String(length=40), nullable=False))
    op.add_column('user', sa.Column('city', sa.String(length=40), nullable=False))
    op.create_unique_constraint(None, 'user', ['city'])
    op.create_unique_constraint(None, 'user', ['user_name'])
    op.create_unique_constraint(None, 'user', ['name'])
    op.create_unique_constraint(None, 'user', ['last_name'])
    op.create_unique_constraint(None, 'user', ['phone'])
    op.create_unique_constraint(None, 'user', ['birthday'])
    op.create_unique_constraint(None, 'user', ['country'])
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'city')
    op.drop_column('user', 'country')
    op.drop_column('user', 'birthday')
    op.drop_column('user', 'phone')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'name')
    op.drop_column('user', 'user_name')
    # ### end Alembic commands ###
