"""empty message

Revision ID: b350d473964e
Revises: 84c8851b9753
Create Date: 2021-06-15 17:01:05.936003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b350d473964e'
down_revision = '84c8851b9753'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('history', table_name='history')
    op.drop_index('vacune', table_name='history')
    op.drop_index('age', table_name='pet')
    op.drop_index('birthday', table_name='pet')
    op.drop_index('gender', table_name='pet')
    op.drop_index('height', table_name='pet')
    op.drop_index('name', table_name='pet')
    op.drop_index('race', table_name='pet')
    op.drop_index('species', table_name='pet')
    op.drop_index('weight', table_name='pet')
    op.drop_index('images', table_name='photo_add')
    op.drop_index('birthday', table_name='user')
    op.drop_index('city', table_name='user')
    op.drop_index('country', table_name='user')
    op.drop_index('last_name', table_name='user')
    op.drop_index('name', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'user', ['name'], unique=False)
    op.create_index('last_name', 'user', ['last_name'], unique=False)
    op.create_index('country', 'user', ['country'], unique=False)
    op.create_index('city', 'user', ['city'], unique=False)
    op.create_index('birthday', 'user', ['birthday'], unique=False)
    op.create_index('images', 'photo_add', ['images'], unique=False)
    op.create_index('weight', 'pet', ['weight'], unique=False)
    op.create_index('species', 'pet', ['species'], unique=False)
    op.create_index('race', 'pet', ['race'], unique=False)
    op.create_index('name', 'pet', ['name'], unique=False)
    op.create_index('height', 'pet', ['height'], unique=False)
    op.create_index('gender', 'pet', ['gender'], unique=False)
    op.create_index('birthday', 'pet', ['birthday'], unique=False)
    op.create_index('age', 'pet', ['age'], unique=False)
    op.create_index('vacune', 'history', ['vacune'], unique=False)
    op.create_index('history', 'history', ['history'], unique=False)
    # ### end Alembic commands ###
