"""empty message

Revision ID: c2c93e2e28c6
Revises: 
Create Date: 2021-06-21 22:37:18.650868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2c93e2e28c6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=40), nullable=False),
    sa.Column('user_name', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('last_name', sa.String(length=40), nullable=False),
    sa.Column('phone', sa.String(length=12), nullable=False),
    sa.Column('birthday', sa.String(length=11), nullable=False),
    sa.Column('country', sa.String(length=40), nullable=False),
    sa.Column('city', sa.String(length=40), nullable=False),
    sa.Column('sal', sa.String(length=40), nullable=False),
    sa.Column('hashed_password', sa.String(length=240), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('pet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('race', sa.String(length=40), nullable=False),
    sa.Column('gender', sa.String(length=40), nullable=False),
    sa.Column('age', sa.String(length=10), nullable=False),
    sa.Column('species', sa.String(length=40), nullable=False),
    sa.Column('weight', sa.String(length=10), nullable=False),
    sa.Column('height', sa.String(length=10), nullable=False),
    sa.Column('birthday', sa.String(length=11), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calendar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start', sa.String(length=50), nullable=False),
    sa.Column('end', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('pet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pet.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('end'),
    sa.UniqueConstraint('title')
    )
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('history', sa.String(length=150), nullable=False),
    sa.Column('history_key', sa.String(length=150), nullable=False),
    sa.Column('vacune', sa.String(length=150), nullable=False),
    sa.Column('token_vacune', sa.String(length=150), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('pet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pet.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('history_key'),
    sa.UniqueConstraint('token_vacune')
    )
    op.create_table('photo_add',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('images', sa.String(length=150), nullable=False),
    sa.Column('token_image', sa.String(length=150), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('pet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pet.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_image')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photo_add')
    op.drop_table('history')
    op.drop_table('calendar')
    op.drop_table('pet')
    op.drop_table('user')
    # ### end Alembic commands ###
