"""empty message

Revision ID: e22084dc913d
Revises: 0d6de7f6acd8
Create Date: 2021-06-19 07:23:16.074572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e22084dc913d'
down_revision = '0d6de7f6acd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('history_key', sa.String(length=40), nullable=False))
    op.add_column('history', sa.Column('token_vacune', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'history', ['token_vacune'])
    op.create_unique_constraint(None, 'history', ['history_key'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'history', type_='unique')
    op.drop_constraint(None, 'history', type_='unique')
    op.drop_column('history', 'token_vacune')
    op.drop_column('history', 'history_key')
    # ### end Alembic commands ###
