"""empty message

Revision ID: f09a3111513c
Revises: 61a72c0b5cd0
Create Date: 2021-06-09 04:38:38.878117

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f09a3111513c'
down_revision = '61a72c0b5cd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_name', sa.String(length=40), nullable=False))
    op.add_column('user', sa.Column('birthday', sa.String(length=11), nullable=False))
    op.drop_index('birtday', table_name='user')
    op.create_unique_constraint(None, 'user', ['last_name'])
    op.create_unique_constraint(None, 'user', ['birthday'])
    op.drop_column('user', 'birtday')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('birtday', mysql.VARCHAR(length=11), nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('birtday', 'user', ['birtday'], unique=False)
    op.drop_column('user', 'birthday')
    op.drop_column('user', 'last_name')
    # ### end Alembic commands ###
